export const instructionsHeadings = [
    "Overview",
    "Phases of Play",
    "Bidding",
    "Card Values",
    "Post-Bidding Phase",
    "Playing Hands",
    "Scoring",
    "Strategy",
    "Additional Notes"
];
export const instructions = [
    [
        "Tysiąc is a Polish trick-taking, trump-based card game for three or four players.",
        "The game uses a standard deck of playing cards, but only uses 9 through Ace.",
        "The goal of the game is to be the first player to reach 1000 points.",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",],
    [
        "First, the dealer shuffles and deals the deck.",
        "<br>",
        "Next, players bid on how many points they think they will be able to score during the game.",
        "The highest bidder will get to play.",
        "If no one bids, the player left of the dealer is forced to play.",
        "<br>",
        "Now, the actual game can start.",
        "Players will alternate playing cards to declare trumps and win tricks.",
        "Whichever player is playing for their bid must earn at least that many points.",
        "<br>",
        "Finally, the scores are tallied, the dealer passes to the left, and a new round begins.",
        "",],
    [
        "Bidding starts with the player left of the dealer, who has a forced bid of 100.",
        "Each player, in turn, may then either raise the previous bid by 10, or pass.",
        "The maximum possible bid is 300, which represents a perfect hand, but players rarely bid past 120.",
        "It is impossible to bid past 120 if you do not have a trump in your hand, because 120 points represents winning all eight tricks.",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",],
    [
        "When bidding, it is important to know how many points your hand can earn you.",
        "<br>",
        "A player has a trump if they have the King and Queen of the same suit.",
        "Declaring a trump on play will score you points: 100 for Hearts, 80 for Diamonds, 60 for Clubs, or 40 for Spades.",
        "<br>",
        "Each individual card is also worth points: 11 for Aces, 10 for 10s, 4 for Kings, 3 for Queens, 2 for Jacks, and 0 for 9s.",
        "The total value of all cards in the game is 120—this is why winning all eight tricks will score you 120 points.",
        "<br>",
        "So, when bidding, it is important to consider the value of all the points you could obtain from both winning tricks and playing trumps.",
        "",
        "",
        "",],
    [
        "Once it has been decided who will be playing for their bid, that player receives the three cards from the widow.",
        "After selecting their desired eight-card hand, that player gives one card away each to the other two players.",
        "Finally, that player may choose to raise their bid if they think they can earn more points.",
        "It is also worth noting that a player may fold once per game if they were forced to bid 100 and they think their hand will not win.",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",],
    [
        "Whichever player is playing for their bid gets to start by playing any card from their hand.",
        "It is important to note that the value of each card also represents which card beats the others—for example, Aces always beat other cards of the same suit.",
        "All other players respond by playing a card from their hand.",
        "The other players must follow suit if possible, and the second player must beat the first player if possible.",
        "The player that wins the trick is the one who played the highest-value card, so long as it matches the original suit.",
        "However, if a player plays a card of the trump suit, that card will beat any card of a regular suit.",
        "<br>",
        "The player who starts the turn can also choose to declare a trump, which will override any previous trump and score them points.",
        "A player can NOT declare a trump if they played second or third.",
        "<br>",
        "",
        "",],
    [
        "Once all 24 cards have been played, the round is over and scoring begins.",
        "<br>",
        "The player playing for their bid needs to have earned at least that much.",
        "If they do, they earn exactly that many points.",
        "If they don't, they lose that many points instead.",
        "<br>",
        "All other players score the cards they've won and the trumps they've played as normal, but must round their total.",
        "Notably, any value ending in a 5 always rounds down (e.g. 35 rounds down to 30).",
        "<br>",
        "Any player with over 900 points will NOT score any points unless they were the player who bid the highest.",
        "This means it is impossible to win unless you are the player who bid.",
        "However, if you successfully bid and reach 1000 points or higher, you win!",],
    [
        "Always start off with cards you know will win, such as Aces or 10s for which you have an Ace of the same suit.",
        "Once you run out of guaranteed wins, declare trumps to earn additional points.",
        "<br>",
        "When bidding, you should consider how many hands you could lose, and how many points that could lose you.",
        "Consider the maximum possible score you could achieve (e.g. 220 if you had the Hearts trump), and subtract the maximum number of points you might not win.",
        "Don't be too reliant on what you MIGHT get from the widow—focus on what you WILL win.",
        "",
        "",
        "",
        "",
        "",
        "",],
    [
        "Finally, it is worth noting that any player who starts with all four 9s in their hand may call a misdeal, forcing the dealer to re-shuffle and re-deal the cards to all players.",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",]
];